database:
    dbname: kaldalis_cms
    host: localhost
    password: "12"
    port: 5432
    sslmode: disable
    timezone: Asia/Shanghai
    user: postgres
jwt:
    auth_cookie: kaldalis_auth
    csrf_cookie: kaldalis_csrf
    path: /
    role_cookie: kaldalis_role
    same_site: 1
    secret: AL3uaHdBI/zK/t0zfeXrFKb/7LOP8LECxp51j7pOo9PP7Ok99JceBQ8k4AZYlOE7tM8sV/55hPq/8I3WdzJi1w==
    secure: false
    ttl: 24h
