database:
  host: localhost
  port: 5432
  user: amber # Replace with your PostgreSQL username
  password: AMBERZz # Replace with your PostgreSQL password
  dbname: kaldalis_cms
  sslmode: disable
  timezone: Asia/Shanghai

jwt:
  secret: "AL3uaHdBI/zK/t0zfeXrFKb/7LOP8LECxp51j7pOo9PP7Ok99JceBQ8k4AZYlOE7tM8sV/55hPq/8I3WdzJi1w==" 
  ttl: 24h
  auth_cookie: kaldalis_auth 
  csrf_cookie: kaldalis_csrf 
  role_cookie: kaldalis_role
  path: /
  domain: 
  secure: false
  same_site: 1
